/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tucil3_13522164;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author acer
 */
public class MainGUI extends javax.swing.JFrame {

    // Local var
    private String startWord;
    private String endWord;
    public static Long time = 0L;
    public static int nodeChecked = 0;


    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 29, 29));
        setName("Main"); // NOI18N

        jTextField1.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jTextField1.setText("StartWord");
        jTextField1.setToolTipText("StartWord");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jTextField2.setText("EndWord");
        jTextField2.setToolTipText("EndWord");

        jLabel1.setBackground(new java.awt.Color(29, 29, 29));
        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Word Ladder Solver");

        jLabel2.setText("Start Word");

        jLabel3.setText("End Word");

        jButton2.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jButton2.setText("UCS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jButton3.setText("Greedy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        jButton4.setText("A*");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 21,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))))
                                .addContainerGap(50, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_startWordActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_startWordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        WordChecker.loadLength(jTextField1.getText().length());

        System.out.println("UCS");
        System.out.println("Start Word: " + jTextField1.getText() + WordChecker.isWordExist(jTextField1.getText()));
        System.out.println("End Word: " + jTextField2.getText() + WordChecker.isWordExist(jTextField2.getText()));

        startWord = jTextField1.getText().toUpperCase();
        endWord = jTextField2.getText().toUpperCase();

        if (WordChecker.isWordExist(startWord) && WordChecker.isWordExist(endWord)) {
            UCS ucs = new UCS(startWord, endWord);
            Result result = ucs.solve();
            if (result.getResult().length > 0){
                ResultUI res = new ResultUI(this, true, result, result.getResult()[0].length);
                res.setVisible(true);
            } else {
                ResultUI res = new ResultUI(this, true, result, 0);
                res.setVisible(true);
            }
        } else {
            System.out.println("Word not found in dictionary");
            JDialog dialog = new WordNotFoundUI(this, true);
            dialog.setVisible(true);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {

        WordChecker.loadLength(jTextField1.getText().length());

        System.out.println("Greedy");
        System.out.println("Start Word: " + jTextField1.getText() + WordChecker.isWordExist(jTextField1.getText()));
        System.out.println("End Word: " + jTextField2.getText() + WordChecker.isWordExist(jTextField2.getText()));

        startWord = jTextField1.getText().toUpperCase();
        endWord = jTextField2.getText().toUpperCase();

        if (WordChecker.isWordExist(startWord) && WordChecker.isWordExist(endWord)) {
            Greedy greedy = new Greedy(startWord, endWord);
            Result result = greedy.solve();
            if (result.getResult().length > 0){
                ResultUI res = new ResultUI(this, true, result, result.getResult()[0].length);
                res.setVisible(true);
            } else {
                ResultUI res = new ResultUI(this, true, result, 0);
                res.setVisible(true);
            }
        } else {
            System.out.println("Word not found in dictionary");
            JDialog dialog = new WordNotFoundUI(this, true);
            dialog.setVisible(true);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AStarActionPerformed

        WordChecker.loadLength(jTextField1.getText().length());

        System.out.println("A*");
        System.out.println("Start Word: " + jTextField1.getText() + WordChecker.isWordExist(jTextField1.getText()));
        System.out.println("End Word: " + jTextField2.getText() + WordChecker.isWordExist(jTextField2.getText()));

        startWord = jTextField1.getText().toUpperCase();
        endWord = jTextField2.getText().toUpperCase();

        if (WordChecker.isWordExist(startWord) && WordChecker.isWordExist(endWord)) {
            AStar aStar = new AStar(startWord, endWord);
            Result result = aStar.solve();
            if (result.getResult().length > 0){
                ResultUI res = new ResultUI(this, true, result, result.getResult()[0].length);
                res.setVisible(true);
            } else {
                ResultUI res = new ResultUI(this, true, result, 0);
                res.setVisible(true);
            }
        } else {
            System.out.println("Word not found in dictionary");
            JDialog dialog = new WordNotFoundUI(this, true);
            dialog.setVisible(true);
        }
    }// GEN-LAST:event_AStarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
